version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot-jpa-relationship
      MYSQL_USER: springboot
      MYSQL_PASSWORD: springboot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

volumes:
  mysql-data:

networks:
  springboot-network:
